// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF7YR2yhtfxafVfaH-JIBCLiOVzgCX9Wg',
    appId: '1:258553526773:web:d0de1d3cfc4af0ac40c8bc',
    messagingSenderId: '258553526773',
    projectId: 'untitled-410a2',
    authDomain: 'untitled-410a2.firebaseapp.com',
    storageBucket: 'untitled-410a2.appspot.com',
    measurementId: 'G-P84ZNPDGHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6i_1wE7-Cch7toE6Rjwv-13A_0p9WxTM',
    appId: '1:258553526773:android:fad420b115b54e3340c8bc',
    messagingSenderId: '258553526773',
    projectId: 'untitled-410a2',
    storageBucket: 'untitled-410a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0GgtEmyZlbl0--FfQTfRc6aFrB2oV8ZI',
    appId: '1:258553526773:ios:484dda54c09ef0c540c8bc',
    messagingSenderId: '258553526773',
    projectId: 'untitled-410a2',
    storageBucket: 'untitled-410a2.appspot.com',
    iosBundleId: 'com.example.untitled1111',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0GgtEmyZlbl0--FfQTfRc6aFrB2oV8ZI',
    appId: '1:258553526773:ios:8af2b730921d229740c8bc',
    messagingSenderId: '258553526773',
    projectId: 'untitled-410a2',
    storageBucket: 'untitled-410a2.appspot.com',
    iosBundleId: 'com.example.untitled1111.RunnerTests',
  );
}
